# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Sync the environment with what is in uv.lock
      run: |
        uv sync --frozen

    - name: Test with pytest
      run: |
        uv run --frozen pytest

    - name: Lint with black
      run: |
        uv run --frozen black --check src/
        uv run --frozen black --check tests/
